### ISSUE TITLE
Recommend upgrading to the real org.json

### ISSUE THREAD

**Issue by stleary** [skyscreamer/JSONassert#179]
[org.json](https://github.com/stleary/JSON-java) now has a public domain license. The latest version is more capable and contains many bug fixes not found in the Android version. Also, you could use similar() for strict comparisons.

**Comment by Brummolix** [comment]
I agree, for example the original version is vulnerable, see https://nvd.nist.gov/vuln/detail/CVE-2023-5072
The (very old) fork may be vulnerable, too.

**Comment by fkriegl** [comment]
Context: currently _skyscreamer/JSONassert_ uses the vaadin implementation of org.json:
https://github.com/skyscreamer/JSONassert/blob/7414e901af11c559bc553e5bb8e12b99a57d1c1c/pom.xml#L52-L56

Instead of using [org.json _aka_ stleary/JSON-java](https://github.com/stleary/JSON-java), **I suggest to switch to the [Open Json](https://github.com/openjson/openjson) reimplementation**, because it has an Apache-2.0 license. Open-Json is based on the original vaadin implementation.

Background:
Developers are fleeing from [stleary/JSON-java](https://github.com/stleary/JSON-java) because of its non-OSI-license. The JSON license was [replaced by a even less specific "Public domain" license in 2022](https://github.com/stleary/JSON-java/commit/6daabb43ab2d32974f2a8ea79d713f67f4c22d30), leaving even more room for interpretation on what this license implies.

See also https://github.com/stleary/JSON-java/issues/331#issuecomment-303515688

**Comment by carterpage** [comment]
I haven't done a new version in a few years, so this will take some time to get the pom.xml modernized. The org.json update will need to be a new minor version at least since it will change how nulls are handled. I'll probably get a 1.5.2 out first to deal with some immediate problems, and then try to fast follow on 1.6.0.

This is not a commercial effort, so I don't have an ETA. However, I will post updates.

**Comment by carterpage** [comment]
Any more thoughts on org.json vs openjson?

org.json is backward breaking in terms of null handling and may require a major update. If openjson does not break the tests, then we could probably release with just a minor bump.

Regardless, it's high time to get off the ancient vaadin library.

**Comment by carterpage** [comment]
Oh, openjson uses different packages. It's perhaps even more backward breaking.

If we were to use org.json, what would be the best version to put in the maven dependency to be as friendly to as many projects as possible? @stleary opinions appreciated.

**Comment by stleary** [comment]
@carterpage I would recommend the org.json latest release: 20240303.

**Comment by fkriegl** [comment]
> Oh, openjson uses different packages. It's perhaps even more backward breaking.

Is this a problem?
How about releasing a new major version with OpenJson? That would not require backward compatibility (and could be picked up in a new spring minor release); and optionally a new minor version with org.json? I know that's twice the work... but I do not see an advantage regarding the license issue when using org.json (which is technically fine).
However, the license of org.json is ["Public Domain"](https://github.com/stleary/JSON-java/blob/master/LICENSE) which is just not formal enough, see my earlier comment regarding that license topic discussion. It would not allow many developers in a corporate context to use the library.

I see two options:
1. The unrealistic one: 
In a new release of org.json, switch to a more formal license (@stleary), that has the same intent as "public domain" but has some "official definition" and by that satiates corporate lawyers. As [already suggested by others](https://github.com/stleary/JSON-java/issues/706#issuecomment-1435351931) org.json could switch to the "Unlicense": 
https://opensource.org/license/unlicense  
Then, JSONassert could use the version released under this new license.

However, [following the closing comment in the issue here](https://github.com/stleary/JSON-java/issues/706#issuecomment-1433131741) I don't think we can expect a change in the license of org.json, as the maintainers do not see a need to change or don't want to acknowledge the problem users are facing with the current license type:
> The author [Douglas Crockford is well aware](https://en.wikipedia.org/wiki/Douglas_Crockford#Software_license_for_%22Good,_not_Evil%22) of the harm he's doing but numerous request from different projects and parties could not change his mind.
  _- https://wiki.debian.org/qa.debian.org/jsonevil_ 

So maybe JSONassert should just follow the maintainer's advice and do not use org.json:
> If Public Domain is not liberal enough for you, I recommend that you do not use it.
  _- https://github.com/stleary/JSON-java/issues/706#issuecomment-1432388496_

2. The higher effort option: 
Use OpenJson or another library with an OSI license type instead and create a new major release.

However, also OpenJson might have drawbacks (how high is the adoption? is there just one maintainer? how often will new (maintenance) release versions be published? etc. )
Maybe also the maintainer of OpenJson (@mfursov) could let us know his thoughts on this.

(Unfortunately) software development is not only about code, but also about legal requirements.
**Without a different license (in org.json) or using another json library that has an OSI license, I personally don't see a chance to confidently use JSONassert in the future.**

**Comment by carterpage** [comment]
@stleary Briefly, can you please help me understand why 20231013 wouldn't be a safer bet?
 * It has the most usages in [central](https://mvnrepository.com/artifact/org.json/json) (for versions <5 years old)
 * It is the oldest commonly used version without any vulnerabilities
 * 20240303 has new public methods (JSONAssert isn't using any of those methods, so maybe this is moot.)

I notice json-java is using a much older version of json-path (upgraded from 2.1 to 2.4 in [20240205](https://github.com/stleary/JSON-java/releases/tag/20240205)), so I'm wondering if latest/greatest is ideal for a low level library.

**Comment by carterpage** [comment]
@stleary Thanks for the recommendation. This will use the new library in the next version.

@fkriegl Thanks for your suggestion. I have opted to use org.json because it is the most widely used JSON library. I am not a lawyer, but plenty of companies with their own lawyers (e.g. Google) seem comfortable with including it in their own open source libraries so that's good enough for me. Feel free to fork JSONAssert to create a version that supports Open JSON!

**Comment by stechio** [comment]
Unfortunately, I'm late to the party 😅 

In 2022, I submitted [an issue](https://github.com/skyscreamer/JSONassert/issues/168) proposing the replacement of the obsolete vaadin implementation of org.json with something like Open JSON: in the meantime I have adapted JSONAssert to Open JSON with great satisfaction, appreciating its flexibility (I needed ordered JSONObject entries for stable and easily inspectable serialization in a testing context).

This week I finally upgraded JSONAssert to version `2.0-rc1`, but [my experience with JSON-java was unpleasant](https://github.com/stleary/JSON-java/issues/972). I understand the merits that made you opt for JSON-java, but it's quite weird the most popular org.json implementation is so poorly designed (not to mention its licensing issue)...
