### ISSUE TITLE
Returns true with strict option turned on when different JSON strings given.

### ISSUE THREAD

**Issue by raduy** [skyscreamer/JSONassert#54]
I've just noticed that JSONAssert returns true when one json contains another - FIRST contains SECOND. Can you confirm that this is NOT a correct behavior?

Also FIRST is not even a valid JSON.

``` groovy
import org.skyscreamer.jsonassert.JSONAssert
import spock.lang.Specification

class JsonAssertTest extends Specification {

    def "should return false when comparing different Jsons"() {
        when:
        JSONAssert.assertEquals(FIRST, SECOND, true)

        then:
        thrown(AssertionError)
    }

    def static String FIRST = """
        {
           "wasSuccessful":true,
           "data":[],
           "message":"Success"
        }
    ],
    "message":"Success"
    }
    """

    def static String SECOND = """
        {
            "wasSuccessful":true,
            "data":[],
            "message":"Success"
        }
    """
}
```

Regards,
Łukasz

**Comment by carterpage** [comment]
Interesting. This is an issue with the JSON library itself, which parses your two strings as:

    FIRST: {"message":"Success","data":[],"wasSuccessful":true}
    SECOND: {"message":"Success","data":[],"wasSuccessful":true}

I agree, I'd expect it to throw a parse error. Since the trees that JSONObject passes to JSONAssert actually are identical, then it's WAI. If you want it fixed, you'd need to do so in the original library.
